<?php

namespace Florale\Bundle\TodolistBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TasklistRepository extends EntityRepository
{
}
