parameters:
    todo.task.type.class: Florale\Bundle\TodolistBundle\Form\Type\TaskType
    todo.tasklist.type.class: Florale\Bundle\TodolistBundle\Form\Type\TasklistType
    
services:

    # FORM TYPE
    todo.task.type:
        class: %todo.task.type.class%
        tags:
            - { name: form.type, alias: task }
            
    todo.tasklist.type:
        class: %todo.tasklist.type.class%
        tags:
            - { name: form.type, alias: tasklist }